"""
Initialization: 
    A main network and a target network with the same initial parameter. 
Goal: 
    Learn an optimal target network to approximate the optimal action values from the experience samples generated by a given behavior policy πb.  

Store the experience samples generated by πb in a replay buffer B = {(s, a, r, s′)} 
    For each iteration, do 
        Uniformly draw a mini-batch of samples from B 
        For each sample (s, a, r, s′), calculate the target value as yT = r + γ maxa∈A(s′) qˆ(s′, a, wT ), where wT is the parameter of the target network 
        Update the main network to minimize (yT − qˆ(s, a, w))2 using the mini-batch of samples 
    Set wT = w every C iterations
"""

import torch
import torch.nn as nn
from GridWorld import HyperParameters, GridWorldEnv
import cv2
import numpy as np
import tqdm


class DQN(GridWorldEnv):

    def __init__(self, HP: HyperParameters, action_space=9, newgrid=False):
        super().__init__(HP, action_space, newgrid)
        self.train_epoch = 50000
        self.episode_length = 100000
        self.lr = 0.01
        self.targe_update_freq = 10  # target network更新频率
        self.batch_size = 100  # 经验回放的批量大小
        self.device = torch.device(
            "mps" if torch.backends.mps.is_available() else "cpu"
        )  
        
        self.main_network = nn.Sequential(
            nn.Linear(2, 128),  # 输入状态（x, y）和动作
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, 512),
            nn.ReLU(),
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, len(self.action_space)),  # 输出Q值
        ).to(
            self.device
        ) 
        self.target_network = nn.Sequential(
            nn.Linear(2, 128),
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, 512),
            nn.ReLU(),
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, len(self.action_space)),
        ).to(
            self.device
        )
        self.target_network.load_state_dict(
            self.main_network.state_dict()
        )  # 将main network权重复制个target network
        self.optimizer = torch.optim.SGD(self.main_network.parameters(), lr=self.lr)
        self.norm_action_space = torch.tensor(
            [self.normalize_action(i) for i in range(len(self.action_space))]
        ).to(
            self.device
        ) 
        self.loss_fn = nn.MSELoss()
        self.replay_buffer = self.initialize_replay_buffer().to(
            self.device
        )  
        self.dataset = torch.utils.data.TensorDataset(
            self.replay_buffer[:, :2],  # state,
            self.replay_buffer[:, 2],  # norm_action
            self.replay_buffer[:, 3],  # action_id
            self.replay_buffer[:, 4],  # reward
            self.replay_buffer[:, 5:7],  # next_state
        )
        self.dataloader = torch.utils.data.DataLoader(
            self.dataset, batch_size=self.batch_size, shuffle=True
        )  

    def initialize_replay_buffer(self):
        replay_buffer = []
        x, y = np.random.randint(0, self.rows), np.random.randint(
            0, self.cols
        )  
        for _ in range(self.episode_length):
            a, ai = self.select_action(x, y)  
            r, (x2, y2) = self.get_next_state_and_reward(
                (x, y), a
            )  
            nx, ny = self.normalize_coordinates(x, y)  
            na = self.normalize_action(ai) 
            nx2, ny2 = self.normalize_coordinates(x2, y2) 
            replay_buffer.append([nx, ny, na, ai, r, nx2, ny2])  
            x, y = x2, y2  
        return torch.tensor(replay_buffer, dtype=torch.float32).to(
            self.device
        )  

    def get_policy(self):
        policy_stable = True
        for x in range(self.rows):
            for y in range(self.cols):
                nx, ny = self.normalize_coordinates(x, y) 
                with torch.no_grad():
                    qvs = self.target_network(
                        torch.tensor([nx, ny], device=self.device)
                    ).squeeze()
             
                max_id = torch.argmax(qvs)

                self.policy[x, y] = self.epsilon_greedy(max_id.item(), self.epsilon)
                sv = np.dot(qvs.cpu().detach().numpy(), self.policy[x, y])
                if (
                    np.abs(self.state_values[x, y] - sv)
                    > self.HP.end_condition
                ):  
                    policy_stable = False
                self.state_values[x, y] = sv

        self.draw_picture(1)  
        return policy_stable 

    def train(self):
        iter = tqdm.tqdm(range(self.train_epoch))
        for epoch in iter:
            losses = []
            for batch in self.dataloader:
                s, na, ai, r, ns = batch
                ai = ai.int()
                #计算main network输出
                m_qvs = self.main_network(s).squeeze() 

                #计算target network输出
                with torch.no_grad():
                    t_qvs = self.target_network(ns).squeeze()
                    t_qmax, _ = t_qvs.max(dim=-1)
                    t_q_next = r + self.gamma * t_qmax

                #更新main network权重
                m_q = m_qvs.gather(-1, ai.unsqueeze(1)).squeeze() #第ai个q-value
                loss = self.loss_fn(m_q, t_q_next)
                losses.append(loss.item())
                self.optimizer.zero_grad()  
                loss.backward() 
                self.optimizer.step()

            iter.set_description(
                f"Epoch {epoch+1}/{self.train_epoch}, ava_loss: {np.mean(losses):.6f}, lr={self.lr:.6f}"
            )  

            #更新target network权重
            if (epoch + 1) % self.targe_update_freq == 0:
                self.target_network.load_state_dict(
                    self.main_network.state_dict()
                ) 
                self.get_policy() 
        self.draw_picture() 


hp = HyperParameters()
hp.gamma = 0.5
hp.rows = 5
hp.cols = 5
env = DQN(hp, action_space=5)
env.train()
