"""Optimal policy learning via Q-learning (on-policy version)
Initialization: 
    αt(s, a) = α > 0 for all (s, a) and all t. ∈ (0, 1). 
    Initial q0(s, a) for all (s, a). 
    Initial -greedy policy π0 derived from q0. 
Goal: 
    Learn an optimal path that can lead the agent to the target state from an initial state s0.  
    
For each episode, do 
    If st (t = 0, 1, 2, . . . ) is not the target state, do 
        Collect the experience sample (at, rt+1, st+1) given st: 
            generate at following πt(st); 
            generate rt+1, st+1 by interacting with the environment. 
        Update q-value for (st, at):  
            qt+1(st, at) = qt(st, at) − αt(st, at)  [  qt(st, at) − (rt+1 + γ maxa qt(st+1, a))  ]  
        Update policy for st:  
            πt+1(a|st) = 1 − |A(st)| (|A(st)| − 1) if a = arg maxa qt+1(st, a) πt+1(a|st) = |A(st)| otherwise
"""

"""Optimal policy learning via Q-learning (off-policy version)
Initialization: 
    αt(s, a) = α > 0 for all (s, a) and all t. 
    Initial guess q0(s, a) for all (s, a). 
    Behavior policy πb(a|s) for all (s, a). 
Goal: 
    Learn an optimal target policy πT for all states from the experience samples generated by πb.  
    
For each episode {s0, a0, r1, s1, a1, r2, . . . } generated by πb, do 
    For each step t = 0, 1, 2, . . . of the episode, do 
        Update q-value for (st, at):  
            qt+1(st, at) = qt(st, at) − αt(st, at)  [  q(st, at) − (rt+1 + γ maxa qt(st+1, a))  ]  
        Update target policy for st:  
            πT,t+1(a|st) = 1 if a = arg maxa qt+1(st, a) πT,t+1(a|st) = 0 otherwise
"""



from GridWorld import GridWorldEnv, HyperParameters
import numpy as np
import tqdm
import torch

class QLearning(GridWorldEnv):

    def __init__(self, HP: HyperParameters, action_space=9, newgrid=False, on_policy=True):
        super().__init__(HP, action_space, newgrid)
        self.lr = 0.1
        self.episode_length = 500
        if on_policy:
            self.reset_on_policy()
        else:
            self.reset_off_policy()

    def reset_on_policy(self):
        super().reset()
        # initial q0
        self.action_values = np.random.random((self.rows, self.cols, len(self.action_space)))
        # initial epsilong-greedy policy pi from q0
        for x in range(self.rows):
            for y in range(self.cols):
                max_id = np.argmax(self.action_values[x, y])
                self.policy[x, y] = self.epsilon_greedy(max_id, self.epsilon)
                if self.grid[x, y] == self.target_flag:
                    self.target_loc = [x, y]
                    break

    def train_on_policy(self):
        iter = tqdm.tqdm(range(self.HP.max_iterations))

        for i in iter:
            stable = True
            x, y = 0, 0 # 从[0, 0] 到 target路径
            while self.target_loc != [x, y]:
                a, ai = self.select_action(x, y)
                r, (x2, y2) = self.get_next_state_and_reward((x, y), a)

                # update q-value
                self.action_values[x, y, ai] = self.action_values[x, y, ai] - self.lr * (
                    self.action_values[x, y, ai] - (r + self.gamma * np.max(self.action_values[x2, y2]))
                    )
                
                # update policy
                max_id = np.argmax(self.action_values[x, y])
                self.policy[x, y] = self.epsilon_greedy(max_id, self.epsilon)
                sv = np.dot(self.policy[x, y], self.action_values[x, y])
                if np.abs(sv - self.state_values[x, y]) > self.HP.end_condition:
                    stable = False
                self.state_values[x, y] = sv
                x, y = x2, y2
            self.draw_picture(1)
            self.lr *= 0.999
            self.epsilon *= 0.999
            iter.set_description(f"lr={self.lr:.6f}, epsilon={self.epsilon:.6f}")
            if stable:
                break

        self.print_optimal_policy()
        self.draw_picture()
        
    def reset_off_policy(self):
        super().reset()
        # 这里b_policy为behavior, 父类中定义的policy为target
        self.b_policy = self.policy.copy()

    def select_action_bpolicy(self, x, y):
        action_index = int(
            torch.distributions.Categorical(torch.FloatTensor(self.b_policy[x, y]))
            .sample()
            .item()
        ) 
        return self.action_space[action_index], action_index

    def train_off_policy(self):
        iter = tqdm.tqdm(range(self.HP.max_iterations))
        for i in iter:
            stable = True
            x, y = np.random.randint(0, self.rows), np.random.randint(0, self.cols)
            for _ in range(self.episode_length):
                a, ai = self.select_action_bpolicy(x, y)
                r, (x2, y2) = self.get_next_state_and_reward((x, y), a)

                # update q-value
                self.action_values[x, y, ai] = self.action_values[x, y, ai] - self.lr * (
                    self.action_values[x, y, ai] - (r + self.gamma * np.max(self.action_values[x2, y2]))
                )

                # update target-policy
                max_id = np.argmax(self.action_values[x, y])
                self.policy[x, y] = self.epsilon_greedy(max_id, 0)
                sv = np.dot(self.action_values[x, y], self.policy[x, y])
                if np.abs(sv - self.state_values[x, y]) > self.HP.end_condition:
                    stable = False
                self.state_values[x, y] = sv
                x, y = x2, y2
            self.draw_picture(1)
            self.lr *= 0.999
            self.epsilon *= 0.999
            iter.set_description(f"lr={self.lr:.6f}, epsilon={self.epsilon:.6f}")
            if stable:
                break

        self.print_optimal_policy()
        self.draw_picture()

    def train(self, on_policy=True):
        if on_policy:
            self.train_on_policy()
        else:
            self.train_off_policy()


hp = HyperParameters()
hp.gamma = 0.5
hp.rows = 5
hp.cols = 5
hp.max_iterations = 100000

on_policy = True
env = QLearning(hp, action_space=5, on_policy=on_policy)
env.train(on_policy)
