"""Optimal policy learning via Q-learning (on-policy version)
Initialization: 
    αt(s, a) = α > 0 for all (s, a) and all t. ∈ (0, 1). 
    Initial q0(s, a) for all (s, a). 
    Initial -greedy policy π0 derived from q0. 
Goal: 
    Learn an optimal path that can lead the agent to the target state from an initial state s0.  
    
For each episode, do 
    If st (t = 0, 1, 2, . . . ) is not the target state, do 
        Collect the experience sample (at, rt+1, st+1) given st: 
            generate at following πt(st); 
            generate rt+1, st+1 by interacting with the environment. 
        Update q-value for (st, at):  
            qt+1(st, at) = qt(st, at) − αt(st, at)  [  qt(st, at) − (rt+1 + γ maxa qt(st+1, a))  ]  
        Update policy for st:  
            πt+1(a|st) = 1 − |A(st)| (|A(st)| − 1) if a = arg maxa qt+1(st, a) πt+1(a|st) = |A(st)| otherwise
"""

"""Optimal policy learning via Q-learning (off-policy version)
Initialization: 
    Initial guess q0(s, a) for all (s, a). 
    Behavior policy πb(a|s) for all (s, a). 
    αt(s, a) = α > 0 for all (s, a) and all t. 
Goal: 
    Learn an optimal target policy πT for all states from the experience samples generated by πb.  
    
For each episode {s0, a0, r1, s1, a1, r2, . . . } generated by πb, do 
    For each step t = 0, 1, 2, . . . of the episode, do 
        Update q-value for (st, at):  
            qt+1(st, at) = qt(st, at) − αt(st, at)  [  q(st, at) − (rt+1 + γ maxa qt(st+1, a))  ]  
        Update target policy for st:  
            πT,t+1(a|st) = 1 if a = arg maxa qt+1(st, a) πT,t+1(a|st) = 0 otherwise
"""


"""
QLearning是一个off-policy的TD算法
之所以是off-policy，是因为，它的targe-policy是从下个状态中所有动作中选择价值最大的动作，而不是由当前策略选择动作
sarsa和MC等算法，都是on-policy的算法，因为它们的target-policy都是由当前策略选择动作的，如果当前策略改变，那么选取的action也会改变
"""

from GridWorld import GridWorldEnv, HyperParameters
import numpy as np
import tqdm


class QLearning(GridWorldEnv):

    def __init__(self, HP: HyperParameters, action_space=9, newgrid=False):
        super().__init__(HP, action_space, newgrid)
        self.sample_episodes = 100000
        self.learning_rate = 0.1

    def reset(self):
        super().reset()
        """重置环境但保持网格不变"""
        self.action_values = np.zeros(
            (self.rows, self.cols, len(self.action_space)), dtype=float
        )  # 每个状态-动作对的价值
        self.optimal_policy = np.zeros(
            (self.rows, self.cols, len(self.action_space)), dtype=int
        )  # 最优策略

    def policy_evaluation(self):
        """评估当前策略，更新状态价值"""
        policy_stable = True
        x, y = np.random.randint(0, self.rows), np.random.randint(
            0, self.cols
        )  # 随机选择一个状态进行更新
        for _ in range(self.sample_episodes):
            a, ai = self.select_action(x, y)  # 根据当前策略选择一个动作
            r, (x2, y2) = self.get_next_state_and_reward(
                (x, y), a
            )  # 执行动作并获得奖励和下一个状态
            # TD(0)更新：Q(s, a) = Q(s, a) - alpha * (Q(s, a) - (reward + gamma * max(Q(s', a')))
            qv = self.action_values[x, y, ai] - self.learning_rate * (
                self.action_values[x, y, ai]
                - (r + self.gamma * np.max(self.action_values[x2, y2]))
            )
            if np.abs(qv - self.action_values[x, y, ai]) > self.HP.end_condition:
                policy_stable = False
            self.action_values[x, y, ai] = qv
            self.policy_improvement(x, y)
            x, y = x2, y2  # 移动到下一个状态

        return policy_stable

    def policy_improvement(self, x, y):
        """策略改进：对每个状态选择最优动作"""

        # 计算每个动作的价值
        qvs = []
        for action in self.action_space:
            r, (x2, y2) = self.get_next_state_and_reward([x, y], action)
            q = r + self.gamma * self.state_values[x2, y2]
            qvs.append(q)

        self.policy[x, y] = self.epsilon_greedy(np.argmax(qvs), self.epsilon)
        # 更新状态价值为当前策略下的期望价值
        self.state_values[x, y] = max(qvs)
        self.draw_picture(wait_time=1)  # 每次策略改进后更新图片显示当前状态价值和策略

    def train(self):
        iter = tqdm.tqdm(range(self.HP.max_iterations))
        for i in iter:
            policy_stable = self.policy_evaluation()
            if policy_stable:
                print(f"Policy converged after {i+1} iterations.")
                break

        self.print_optimal_policy()
        self.draw_picture()


hp = HyperParameters()
hp.gamma = 0.9
hp.rows = 5
hp.cols = 5
env = QLearning(hp)
env.train()
