"""state-value function approximation
Initialization: 
    A function vˆ(s, w) that is a differentiable in w. Initial parameter w_{0}.
Goal: 
    Learn the true state values of a given policy π.

For each episode {(s_{t}, r_{t+1}, s_{t+1})}_{t} generated by π, do
    For each sample (s_t, r_t+1, s_t+1), do
        In the general case:
            w_{t+1} = w_{t}+α_{t} [r_{t+1} + γ vˆ(s_{t+1}, w_{t}) − vˆ(s_t, w_t)] ∇_{w}vˆ(s_{t}, w_{t})
        In the linear case:
            w_{t+1} = w_{t} + α_{t}  [r_{t+1} + γφ^{T} (s_{t+1})w_t − φ^{T} (s_t)w_t   ]φ(s_{t})
"""

import numpy as np
import tqdm
from GridWorld import GridWorldEnv, HyperParameters
import cv2


class TDLinear(GridWorldEnv):

    def __init__(self, HP: HyperParameters, action_space=9, newgrid=False):
        super().__init__(HP, action_space, newgrid)
        self.episode_length = 500 * 200
        self.lr = 0.001
        
        # v(s, w)是s的函数，对于s的坐标x,y有 v(s, w) = w[0]*x + w[1]*y + w[2]，这里我们用一个简单的线性函数逼近来估计状态-动作价值
        # 对于x,y,x*y,x^2,y^2等特征进行线性组合来逼近状态值，有v(s, w) = w[0]*x + w[1]*y + w[2]*x*y + w[3]*x^2 + w[4]*y^2 + w[5]，这里我们用一个简单的线性函数逼近来估计状态-动作价值
        self.function_weights = np.random.random(
            len(["x", "y", "x*y", "x^2", "y^2", "x^2*y", "y^2*x", "x^2*y^2", "1"])
        )  # 线性函数逼近的权重，包含x,y,1三个特征的权重
        self.function_weights[-1] = 1

    def reset(self):
        super().reset()
        # 初始化一个随机的策略
        self.action_values = np.random.random((self.rows, self.cols, len(self.action_space)))
        for x in range(self.rows):
            for y in range(self.cols):
                max_id = np.argmax(self.action_values[x, y])
                self.policy[x, y] = self.epsilon_greedy(max_id, self.epsilon)

    def v_feature(self, norm_x, norm_y):
        return np.array(
            [
                norm_x,
                norm_y,
                norm_x * norm_y,
                norm_x**2,
                norm_y**2,
                norm_x**2*norm_y,
                norm_y**2*norm_x,
                norm_x**2*norm_y**2,
                1,
            ]
        )

    def v_value(self, norm_x, norm_y):
        return np.dot(self.function_weights, self.v_feature(norm_x, norm_y))

    def TD_Episode(self):
        """评估当前策略，更新状态价值"""
        x, y = np.random.randint(0, self.rows), np.random.randint(
            0, self.cols
        )  # 随机选择一个初始状态
        stable = True
        for _ in range(self.episode_length):
            a, ai = self.select_action(x, y) 
            nx, ny = self.normalize_coordinates(x, y)  # 归一化坐标

            # 执行动作并获得奖励和下一个状态
            r, (x2, y2) = self.get_next_state_and_reward((x, y), a)
            nx2, ny2 = self.normalize_coordinates(x2, y2)  # 归一化坐标

            # value update 权重更新
            sv = self.v_value(nx, ny)
            sv2 = self.v_value(nx2, ny2)
            self.function_weights = self.function_weights - self.lr * (
                sv - (r + self.gamma * sv2)
            ) * (self.v_feature(nx, ny))


            sv = self.v_value(nx, ny)
            if np.abs(sv - self.state_values[x, y]) > self.HP.end_condition:
                stable = False
            self.state_values[x, y] = sv
            x, y = x2, y2  # 移动到下一个
        return stable


    def train(self):
        iter = tqdm.tqdm(range(self.HP.max_iterations))
        for i in iter:
            policy_stable = self.TD_Episode()

            self.lr *= 0.999
            iter.set_description(f"lr={self.lr:.6f}")
            self.draw_picture(1)
            if policy_stable:
                print(f"\nPolicy iteration converged after {i + 1} iterations!")
                break
        self.print_optimal_policy()
        self.draw_picture()


hp = HyperParameters()
hp.gamma = 0.9
hp.rows = 5
hp.cols = 5
env = TDLinear(hp)
env.train()
